apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: NodePort
  ports:
    - targetPort: 5000
      port: 5000
      nodePort: 30003
  selector:
    name: python-app-pod
    app: python-app
    type: frontend

